language: python
cache: pip
# env:
#   - PR_AUTHOR=${TRAVIS_PULL_REQUEST_SLUG::-15}
git:
  depth: 2
jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
  include:
    # fail if asciidoctor encounters errors
    - stage: validate
      name: "Validate updated assemblies with Asciidoctor"
      install:
        - gem install asciidoctor
        - gem install asciidoctor-diagram
        - gem install rouge
      script:
        - chmod +x ./scripts/check-asciidoctor-build.sh
        - ./scripts/check-asciidoctor-build.sh
    - stage: build
      name: "Build openshift-enterprise distro"
      before_install:
        - gem install asciidoctor
        - gem install asciidoctor-diagram
      install:
        - pip3 install pyyaml
        - pip3 install aura.tar.gz
      script:
        - python3 build.py --distro openshift-builds --product "Builds for Red Hat OpenShift" --version 1.0 --no-upstream-fetch && python3 makeBuild.py

    - stage: netlify
      env:
        - CAN_FAIL=true
      language: minimal
      if: type IN (pull_request) AND branch IN (main, enterprise-4.13, enterprise-4.14) AND sender != "openshift-cherrypick-robot"
      script:
        - chmod +x autopreview.sh && ./autopreview.sh

stages:
  - validate
  - build
  - netlify
  #- check-with-vale
  #- automerge
