language: python
cache:
  pip: true
  directories:
    - /home/travis/.rvm/gems
# env:
#   - PR_AUTHOR=${TRAVIS_PULL_REQUEST_SLUG::-15}
git:
  depth: 2
jobs:
  allow_failures:
    env:
      - CAN_FAIL=true

  include:
    - stage: cache-and-validate
      name: "Create install cache and validate updated assemblies"
      install:
        - gem install asciidoctor asciidoctor-diagram rouge
        - pip3 install pyyaml aura.tar.gz
      script:
        # Fail if Asciidoctor encounters errors. Run only if there are modified AsciiDoc files
        - if ! [[ -z $(git diff --name-only HEAD~1 HEAD --diff-filter=d '*.adoc' ':(exclude)_unused_topics/*') ]]; then chmod +x ./scripts/check-asciidoctor-build.sh && ./scripts/check-asciidoctor-build.sh; fi

    - stage: build
      name: "Build openshift-pipelines distro"
      script:
        - python3 build.py --distro openshift-pipelines --product "OpenShift Pipelines" --version 1.11 --no-upstream-fetch && python3 makeBuild.py

    - stage: netlify
      env:
        - CAN_FAIL=true
      language: minimal
      if: type IN (pull_request) AND branch IN (pipelines-docs, pipelines-docs-1.11, pipelines-docs-1.12, pipelines-docs-1.13, pipelines-docs-1.14) AND sender != "openshift-cherrypick-robot"
      script:
        - chmod +x autopreview.sh
        - ./autopreview.sh

stages:
  - cache-and-validate
  - build
  - netlify
